#!/bin/sh

/usr/sbin/addsudo /bin/wget app-wordpress
/usr/sbin/addsudo /bin/zip app-wordpress
/usr/sbin/addsudo /bin/zip app-wordpress
/usr/sbin/addsudo /bin/unzip app-wordpress
/usr/sbin/addsudo /bin/cp app-wordpress
/usr/sbin/addsudo /bin/mv app-wordpress

